In [18]:
import pickle
# Import libraries
import streamlit as st
import numpy as np
import pandas as pd
import pickle
import warnings
warnings.filterwarnings('ignore')

In [19]:
# Reading the pickle files that we created before 
rf_pickle = open('randomforest_fetalhealth.pickle', 'rb') 
clf = pickle.load(rf_pickle)
rf_pickle.close()

In [20]:
# loading data
user_data = pd.read_csv('fetal_health_user.csv')
predictions = clf.predict(user_data)
print(predictions)

[1. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3.]


In [22]:
np.max(clf.predict_proba(user_data), axis = 1)
# print(probabilities)

array([0.9999179 , 0.83411025, 0.95853834, 0.95170748, 0.99972202,
       0.87520723, 0.89787463, 0.56771187, 0.77275732, 0.95302083,
       0.99322917, 0.99375   , 0.89704985, 0.98932292, 0.98619792,
       0.99244792])

In [5]:
user_data['Predictions'] = predictions
user_data

baseline value  accelerations  fetal_movement  uterine_contractions  \
0              123          0.004           0.000                 0.005   
1              123          0.000           0.000                 0.005   
2              123          0.000           0.000                 0.005   
3              123          0.000           0.000                 0.005   
4              123          0.006           0.000                 0.006   
5              138          0.000           0.009                 0.002   
6              141          0.000           0.017                 0.002   
7              141          0.005           0.023                 0.002   
8              141          0.001           0.020                 0.001   
9              129          0.000           0.001                 0.006   
10             129          0.000           0.001                 0.006   
11             129          0.000           0.001                 0.005   
12             129          0.000           0.001                 0.007   
13             129          0.000           0.001                 0.006   
14             129          0.000           0.001                 0.006   
15             129          0.000           0.001                 0.006   

    light_decelerations  severe_decelerations  prolongued_decelerations  \
0                 0.005                     0                     0.000   
1                 0.004                     0                     0.000   
2                 0.005                     0                     0.000   
3                 0.006                     0                     0.000   
4                 0.004                     0                     0.000   
5                 0.002                     0                     0.000   
6                 0.002                     0                     0.000   
7                 0.001                     0                     0.000   
8                 0.001                     0                     0.000   
9                 0.009                     0                     0.001   
10                0.008                     0                     0.002   
11                0.008                     0                     0.002   
12                0.007                     0                     0.002   
13                0.006                     0                     0.003   
14                0.005                     0                     0.003   
15                0.006                     0                     0.002   

    abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                                24                                   1.3   
1                                47                                   1.1   
2                                50                                   0.8   
3                                45                                   1.0   
4                                33                                   1.3   
5                                60                                   0.5   
6                                60                                   0.4   
7                                53                                   1.0   
8                                59                                   0.5   
9                                65                                   2.8   
10                               65                                   2.8   
11                               65                                   2.9   
12                               65                                   3.1   
13                               66                                   2.9   
14                               66                                   2.8   
15                               66                                   3.2   

    percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                                   0       ...   
1       

In [12]:
# user_data['Probabilities'] = probabilities
print(probabilities)
print(np.max(probabilities))

[[9.99917902e-01 7.81718887e-05 3.92587940e-06]
 [8.34110246e-01 1.58333745e-01 7.55600921e-03]
 [9.58538342e-01 4.14577319e-02 3.92587940e-06]
 [9.51707477e-01 4.82885972e-02 3.92587940e-06]
 [9.99722022e-01 2.77978462e-04 0.00000000e+00]
 [1.16459435e-01 8.75207232e-01 8.33333333e-03]
 [5.81423611e-02 8.97874635e-01 4.39830044e-02]
 [4.29163127e-01 5.67711873e-01 3.12500000e-03]
 [2.24117684e-01 7.72757316e-01 3.12500000e-03]
 [3.80985169e-02 8.88064972e-03 9.53020833e-01]
 [2.60416667e-03 4.16666667e-03 9.93229167e-01]
 [2.08333333e-03 4.16666667e-03 9.93750000e-01]
 [9.90438988e-02 3.90625000e-03 8.97049851e-01]
 [7.55208333e-03 3.12500000e-03 9.89322917e-01]
 [1.06770833e-02 3.12500000e-03 9.86197917e-01]
 [3.38541667e-03 4.16666667e-03 9.92447917e-01]]


TypeError: 'axis' is an invalid keyword argument for print()